name: second-attempt-to-actions
on: [push]
jobs:
  check-os:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: uname -a
      - run: hostname
  check-current-pwd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: hostname
      - run: pwd
      - run: whoami
      - run: echo $PATH
