name: gcloud-actions
on: [push]
jobs:
  install-gcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: GoogleCloudPlatform/github-actions@0.1.2
      - run: gcloud --help
      - run: gcloud config list