name: gcloud-actions
on: [push]
jobs:
  install-gcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-gcloud@0.1.2
      - uses: actions/setup-node@v1
      - run: gcloud --help
      - run: gcloud config list